# Generated by Django 2.1.7 on 2026-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='dishes/')),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Meals', 'Meals'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian')], max_length=20)),
            ],
        ),
    ]
